posters:
  - username: wpr101
    display_name: "wpr101"
    active: true

  - username: anthonyms
    display_name: "Ant"
    active: true

  - username: prust04
    display_name: "prust04"
    active: true
